Images of bot
SRA-VJTI/MARIO pull request #16
Opened 2022-06-11 15:48 UTC by Ris-Bali

This PR adds the latest images for the Mario Bot .

2022-06-13 07:24 UTC, Ris-Bali commented
@MOLOCH-dev Pls Review

2022-06-14 05:08 UTC, MOLOCH-dev requested changes

2022-06-14 05:08 UTC, MOLOCH-dev commented on README.md
> +![bot gif](assets/Gif2_AdobeExpress.gif)
Center all images and gifs

2022-06-14 05:08 UTC, MOLOCH-dev commented on README.md
> +![Bot Pic](assets/bot2.png)
Center this image

2022-06-14 05:08 UTC, MOLOCH-dev commented on README.md
> +![simulation](assets/simulation.png)
Center align this image

2022-06-14 21:12 UTC, Ris-Bali commented
I have resolved the alignment issues

2022-06-15 12:10 UTC, gautam-dev-maker commented
Image under"4_simulation_gazebo" is still outdated, kindly update it as well. 
Also add the images of rviz simulation in "3_simulation_rviz".

2022-06-16 06:56 UTC, toshan-luktuke commented
I've updated the images in `4_simulation_gazebo` and `3_simulation_rviz` with my PR which has been merged

2022-06-16 07:05 UTC, MOLOCH-dev approved these changes

2022-06-16 07:06 UTC, merged